image: docker:latest
services:
    - docker:dind

stages:
    - build
    - test
    - release

variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    CONTAINER_ACTIVE_TEST: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-active.test
    CONTAINER_MAIN_IMAGE: $CI_REGISTRY_IMAGE:main
    CONTAINER_ACTIVE_IMAGE: $CI_REGISTRY_IMAGE:active

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-active:
    stage: build
    script:
        - docker build . --pull -t ${CONTAINER_ACTIVE_TEST} --build-arg SERIES="active"
        - docker push ${CONTAINER_ACTIVE_TEST}

test-active:
    stage: test
    needs: ["build-active"]
    script:
        - docker pull $CONTAINER_ACTIVE_TEST
        - docker run $CONTAINER_ACTIVE_TEST /usr/local/bin/test_pythons.py
        - docker run $CONTAINER_ACTIVE_TEST tox --version
        - docker run $CONTAINER_ACTIVE_TEST mypy --version
        - docker run $CONTAINER_ACTIVE_TEST pipx --version

release-image:
    stage: release
    needs: [test-active]
    script:
        - docker pull $CONTAINER_ACTIVE_TEST
        - docker tag $CONTAINER_ACTIVE_TEST $CONTAINER_ACTIVE_IMAGE
        - docker push $CONTAINER_ACTIVE_IMAGE
        - docker tag $CONTAINER_ACTIVE_TEST $CONTAINER_MAIN_IMAGE
        - docker push $CONTAINER_MAIN_IMAGE
    only:
        - main

test-readme:
    stage: test
    needs: []
    services: []
    before_script: []
    image: python:alpine
    script:
        - apk add git
        - ./get_versions.py
        - ./sync_readme.py
        - git diff --exit-code
