image: docker:latest
services:
    - docker:latest

stages:
    - build
    - test
    - release
    - deploy

variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
    stage: build
    script:
        - docker build --pull -t $CONTAINER_TEST_IMAGE .
        - docker push $CONTAINER_TEST_IMAGE

test1:
    stage: test
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests

test2:
    stage: test
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

release-image:
    stage: release
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
  only:
        - main

deploy:
    stage: deploy
    script:
        - ./deploy.sh
    only:
        - main


# image: docker:latest
# services:
# - docker:dind

# stages:
# - build

# variables:
#   RELEASE_IMAGE: quay.io/python-devs/ci-image:master
#   LATEST_IMAGE: quay.io/python-devs/ci-image:latest

# build:
#   stage: build
#   script:
#     - docker login -u="python-devs+gitlabci" -p="$CI_JOB_TOKEN" quay.io
#     - docker build --pull -t $RELEASE_IMAGE .
#     - docker push $RELEASE_IMAGE
#     - docker tag $RELEASE_IMAGE $LATEST_IMAGE
#     - docker push $LATEST_IMAGE
#   only:
#     - master@python-devs/ci-images

# build-fork:
#   stage: build
#   script:
#     - docker build --pull -t $RELEASE_IMAGE .
#   except:
#     - master@python-devs/ci-images
